### ISSUE TITLE
3D HUBS

### ISSUE THREAD

**Issue by buildog** [matrix-io/MATRIX-Creator-Case#1]
via 3DHUBS I got a warning about a possible wrong scale when uploading the file :-)

![capture d ecran 2016-11-16 a 13 16 21](https://cloud.githubusercontent.com/assets/18439883/20346956/24623ff6-abff-11e6-9939-2c60fa385b6b.png)

**Comment by AlieGG** [comment]
Sorry for the late reply buildog, but I was able to upload them to 3D Hubs without a problem.

Here is a picture of what my screen looked like after I uploaded it to 3D Hubs.

<img width="1167" alt="screen shot 2016-11-30 at 11 56 01 am" src="https://cloud.githubusercontent.com/assets/18622203/20762381/2b5e278e-b6f4-11e6-9851-9434e64fa8a6.png">
